### ISSUE TITLE
issue with 1.13.2

### ISSUE THREAD

**Issue by AltQuest** [AltQuest/EmeraldQuest-HackerIsland#2]
the issue ONLY appears AFTER/AS a player logs in.
it allows player to stay logged in. not sure why but heres the console:

emeraldquest | [02:59:09 INFO]: EmeraldQuest starting
emeraldquest | [02:59:10 INFO]: Unknown command. Type "/help" for help.
emeraldquest | [02:59:10 INFO]: Server permissions file permissions.yml is empty, ignoring it
emeraldquest | [02:59:10 INFO]: Done (43.386s)! For help, type "help"
emeraldquest | [03:00:42 INFO]: UUID of player bitcoinjake09 is bceeaefc-9590-4233-a858-d3eb933121ec
emeraldquest | [03:00:42 ERROR]: Could not pass event PlayerJoinEvent to EmeraldQuest v2.0
emeraldquest | org.bukkit.event.EventException: null
emeraldquest | 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:344) [spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:163) [spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:150) [spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	at net.minecraft.server.v1_13_R2.LoginListener.Y_(LoginListener.java:54) [spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:231) [spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:120) [spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:998) [spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
emeraldquest | Caused by: java.lang.NullPointerException
emeraldquest | 	at com.emeraldquest.emeraldquest.EmeraldQuest.setPlayerMaxHealth(EmeraldQuest.java:412) ~[?:?]
emeraldquest | 	at com.emeraldquest.emeraldquest.EmeraldQuest.setTotalExperience(EmeraldQuest.java:403) ~[?:?]
emeraldquest | 	at com.emeraldquest.emeraldquest.EntityEvents.onPlayerJoin(EntityEvents.java:144) ~[?:?]
emeraldquest | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
emeraldquest | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
emeraldquest | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
emeraldquest | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
emeraldquest | 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-e769fe4-068dab5]
emeraldquest | 	... 14 more
emeraldquest | [03:00:43 INFO]: bitcoinjake09[/xxx.xx.x.x:xxxxx] logged in with entity id 326 at ([world]23.5, 67.0, 73.5)

**Comment by AltQuest** [comment]
main errors:

emeraldquest | Caused by: java.lang.NullPointerException
emeraldquest | 	at com.emeraldquest.emeraldquest.EmeraldQuest.setPlayerMaxHealth(EmeraldQuest.java:412) ~[?:?]
emeraldquest | 	at com.emeraldquest.emeraldquest.EmeraldQuest.setTotalExperience(EmeraldQuest.java:403) ~[?:?]
emeraldquest | 	at com.emeraldquest.emeraldquest.EntityEvents.onPlayerJoin(EntityEvents.java:144) ~[?:?]

**Comment by AltQuest** [comment]
i found the root of the problem...
So... My error that I get with login is due to my /mod flag command and the fact that when its off its = null which basically means nothing. Gonna have to change some codes to false. But after that 1.13.2 should be stable :D

if i login in and do /mod flag and its on and i log out and back in i do not get the error.

**Comment by AltQuest** [comment]
this is fixed and server should be stable with 1.13.2 for now!
